[auth]
# This sets the main site URL for the Supabase instance.
# It's used for constructing redirect URLs and is a primary check for CORS.
site_url = "http://localhost:3000"

# This is an allow-list for additional redirect URLs.
# We add the frontend's URL here to ensure that Supabase allows redirects back to your application after authentication.
additional_redirect_urls = ["http://localhost:3000"]
