-- 1. Create the table to store canonical shift titles and their default settings
CREATE TABLE IF NOT EXISTS "public"."shift_templates" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" uuid NOT NULL,
    "title" text NOT NULL,
    "default_shift_type" text,
    "default_length_hours" numeric,
    "default_goal_wrvu_per_hour" numeric(5,2),
    CONSTRAINT "shift_templates_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "shift_templates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT "shift_templates_user_id_title_key" UNIQUE (user_id, title) -- Ensures a user can't have duplicate titles
);

-- 2. Enable Row Level Security for the new table
ALTER TABLE "public"."shift_templates" ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy so users can only manage their own templates
CREATE POLICY "Users can manage their own shift templates." ON "public"."shift_templates"
    FOR ALL USING (("auth"."uid"() = "user_id"));
