# This GitHub Action workflow is triggered on every push to the 'main' branch.
# It uses the Supabase CLI to deploy any new database migrations to your Supabase project.
#
# Workflow Steps:
# 1. Checks out the repository's code.
# 2. Sets up the Supabase CLI in the runner environment.
# 3. Pushes the database migrations directly using the database connection URL.

name: Push Supabase Migrations

on:
  push:
    branches:
      - main # This action runs only on pushes to the main branch

jobs:
  push_migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest # Use the latest version of the Supabase CLI

      - name: Push Database Migrations
        env:
          # Your Supabase access token, stored as a GitHub Secret
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          # The database password, which is used to construct the DB URL
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          # Your Supabase project ID, used to construct the DB URL
          SUPABASE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          # Push migrations directly to the database using the connection URL.
          # This is the recommended non-interactive method for CI/CD.
          supabase db push --db-url "postgres://postgres:${SUPABASE_DB_PASSWORD}@db.${SUPABASE_PROJECT_ID}.supabase.co:5432/postgres"

